'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { downloadCard } from '../../lib/card-export';
import Keepsake from './keepsake';
import { buildStory } from '../../lib/story.mjs';
function Picture({src,label,className=''}) {
  const [failed,setFailed]=useState(false);
  return src&&!failed?<img className={className} src={src.startsWith('https://cdn.myanimelist.net/')?'/api/image?src='+encodeURIComponent(src):src} alt={label} referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<span className={`${className} fx-placeholder`} aria-label={label}>{label.slice(0,1)}</span>;
}
function CoverPop({items,repeat=false}) { return <div className="cover-pop" aria-label={repeat?'Titles revisited':'Selected completed titles'}>{items.map((item,index)=><figure key={item.id} style={{'--pop':index}}><Picture className="pop-image" src={item.cover} label={item.title}/><figcaption title={item.title}>{item.title}</figcaption>{repeat&&<small>{item.repeatCount>0?item.repeatCount+' recorded '+(item.repeatCount===1?'repeat':'repeats'):''}{item.isRepeating?(item.repeatCount>0?' · Active now':'Active now'):''}</small>}</figure>)}</div>; }
function CoverMontage({items}) {
 const [batch,setBatch]=useState(0),[playing,setPlaying]=useState(true);const size=5;
 useEffect(()=>{if(!playing||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=setInterval(()=>{if(!document.hidden)setBatch(x=>(x+1)%Math.ceil(items.length/size));},3400);return()=>clearInterval(timer);},[items.length,playing]);
 const visible=Array.from({length:Math.min(size,items.length)},(_,i)=>items[(batch*size+i)%items.length]);
 return <div className="cover-montage" aria-live="off"><CoverPop key={batch} items={visible}/>{items.length>size&&<div className="montage-controls"><button onClick={()=>setPlaying(!playing)}>{playing?'Pause covers':'Play covers'}</button><button onClick={()=>setBatch(x=>(x+1)%Math.ceil(items.length/size))}>More covers ↗</button></div>}</div>;
}
function Headline({slide}) { const parts=slide.emphasis?slide.title.split(slide.emphasis):null; return <h2 className="fx-headline">{parts?<><span className="fx-line">{parts[0]}</span><strong className="fx-line">{slide.emphasis}</strong>{parts[1]&&<span className="fx-line">{parts[1]}</span>}</>:<span className="fx-line">{slide.title}</span>}</h2>; }
function Scene({slide,data,name,avatar,period,sample}) {
  if(slide.type==='repeat-covers')return <><Headline slide={slide}/><p className="fx-scope">ALL-TIME RECORDS · {`${slide.start+1}–${slide.start+slide.items.length} OF ${slide.total} TITLES`}</p><CoverPop items={slide.items} repeat/><p className="fx-quip fx-arrive">{slide.quip}</p></>;
  if(slide.type==='badges')return <><Headline slide={slide}/><p className="fx-scope">{slide.total} OFFICIAL MAL BADGES · {period==='all'?'ALL TIME':period}</p><CoverPop items={slide.items}/><p className="fx-quip">{slide.quip}</p></>;
  if(slide.type==='closing')return <Keepsake data={data} name={name} avatar={avatar} period={period} awards={slide.awards} sample={sample}/>;
  if(slide.type==='awards')return <><p className="fx-scope">WRAPPED AWARDS · NOT MAL EVENT BADGES</p><Headline slide={slide}/><div className="taste-awards">{slide.awards.map(a=><section key={a.kind} className="fx-arrive"><div className="taste-portrait" role="img" aria-label={a.genre+" inspired portrait"} style={{backgroundPosition:`${a.portrait%3*50}% ${Math.floor(a.portrait/3)*50}%`}}/><h3>{a.title}</h3><p>{a.count} completed {a.kind} titles tagged {a.genre}.</p></section>)}</div></>;
  if(slide.type==='character')return <><p className="fx-scope">A PLAYFUL {slide.kind.toUpperCase()} MATCH</p><Headline slide={slide}/><Picture className="character-portrait fx-arrive" src={slide.award.character.image} label={slide.award.character.name}/><h3 className="character-name fx-arrive">{slide.award.character.name}</h3><p className="fx-subtitle fx-arrive">{slide.award.character.series}</p><p className="fx-quip fx-arrive">{slide.award.character.line}</p><p className="fx-scope">Matched from your leading genre: {slide.award.genre}.</p></>;
  if(slide.type==='opening')return <><Picture className="fx-avatar fx-arrive" src={avatar} label={name||'You'}/><p className="fx-hello fx-arrive">Hey, {name||'you'}.</p><Headline slide={slide}/><p className="fx-quip fx-arrive">{slide.quip}</p></>;
  if(slide.type==='question')return <><span className="fx-question-mark fx-arrive" aria-hidden="true">?</span><Headline slide={slide}/><p className="fx-quip fx-arrive">{slide.quip}</p></>;
  if(['count','number','month'].includes(slide.type))return <>{slide.eyebrow&&<p className="fx-callout fx-arrive">{slide.eyebrow}</p>}{slide.type!=='count'&&<Headline slide={slide}/>}<div className="fx-number fx-arrive">{slide.value}{slide.type==='number'&&<small>{slide.unit}</small>}</div>{slide.type==='count'&&<Headline slide={slide}/>} {slide.type==='count'&&slide.items?.length>0&&<CoverMontage items={slide.items}/>} {slide.scope&&<p className="fx-scope">{slide.scope}</p>} {slide.type==='month'&&<p className="fx-unit fx-arrive">{slide.unit}</p>}<p className="fx-quip fx-arrive">{slide.quip}</p></>;
  if(slide.type==='spotlight')return <><p className="fx-callout fx-arrive">{slide.title}</p><Picture key={slide.item.id} className="fx-hero-cover fx-arrive" src={slide.item.cover} label={slide.item.title}/><h2 className="fx-title fx-arrive">{slide.item.title}</h2><strong className="fx-score fx-arrive">{slide.item[slide.metric]}<small>{slide.unit}</small></strong>{slide.scope&&<span className="fx-scope fx-arrive">{slide.scope}</span>}<p className="fx-quip fx-arrive">{slide.quip}</p></>;
  if(slide.type==='ranking')return <><Headline slide={slide}/>{slide.subtitle&&<p className="fx-subtitle fx-arrive">{slide.subtitle}</p>}<ol className="fx-ranking">{slide.items.map((item,index)=><li className="fx-arrive" key={item.id} style={{'--order':index+1}}><span>{slide.shared?"★":index+1}</span><Picture className="fx-small-cover" src={item.cover} label={item.title}/><div title={item.title}>{item.title}</div><strong>{item[slide.metric]}<small>{slide.unit}</small></strong></li>)}</ol><p className="fx-quip fx-arrive">{slide.quip}</p></>;
  if(slide.type==='categories')return <><h2 className="fx-arrive">{slide.title}</h2><ol className="fx-categories">{slide.rows.map((row,index)=><li className="fx-arrive" key={row.id} style={{'--order':index+1}}><span>0{index+1}</span><div title={row.name}>{row.name}<small>{row.count} {row.count===1?'title':'titles'}</small></div></li>)}</ol><p className="fx-quip fx-arrive">{slide.quip}</p></>;
  if(slide.type==='repeats')return <><span className="fx-loop fx-arrive" aria-hidden="true">↺</span><h2 className="fx-arrive">{slide.title}</h2><div className="fx-repeat-stats fx-arrive"><div><strong>{data.anime.repeats.known?data.anime.repeats.count:'—'}</strong><span>rewatches</span></div><div><strong>{data.manga.repeats.known?data.manga.repeats.count:'—'}</strong><span>rereads</span></div></div><p className="fx-scope fx-arrive">ALL-TIME COUNTS</p><p className="fx-quip fx-arrive">{slide.quip}</p></>;
  return <><p className="fx-eyebrow fx-arrive">{name||'YOUR'} / {period==='all'?'ALL TIME':period}</p><h2 className="fx-arrive">{slide.title}</h2><div className="fx-repeat-stats fx-arrive"><div><strong>{data.anime.count}</strong><span>anime completed</span></div><div><strong>{data.manga.count}</strong><span>manga completed</span></div></div><div className="fx-final-covers fx-arrive">{[['anime',data.anime],['manga',data.manga]].map(([kind,s])=>s.highest[0]&&<Picture key={kind} src={s.highest[0].cover} label={s.highest[0].title} className="fx-ending-cover"/>)}</div><p className="fx-quip fx-arrive">{slide.quip}</p></>;
}
export default function PersonalRecap({anime,manga,period,asOf,name,avatar,badges}) {
  const {slides,data}=useMemo(()=>buildStory(anime,manga,period,asOf,badges),[anime,manga,period,asOf,badges]);
  const [step,setStep]=useState(0),[open,setOpen]=useState(true),[info,setInfo]=useState(false);
  const dialog=useRef(null),launcher=useRef(null),surface=useRef(null),gesture=useRef(null),suppressClick=useRef(0);
  const [exporting,setExporting]=useState(false),[exportMessage,setExportMessage]=useState('');
  const slide=slides[Math.min(step,slides.length-1)];
  async function saveCard(){setExporting(true);setExportMessage('');try{await downloadCard(surface.current,`mal-wrapped-${period}-${slide.id}.png`);setExportMessage('Card downloaded.');}catch{setExportMessage('Download failed. Please try again.');}finally{setExporting(false);}}
  const infoClose=useRef(null),infoTrigger=useRef(null);
  useEffect(()=>{if(info)infoClose.current?.focus({preventScroll:true});},[info]);
  function closeInfo(){setInfo(false);infoTrigger.current?.focus({preventScroll:true});}
  const covers=useMemo(()=>[...anime,...manga].filter(x=>x.cover).slice(0,8),[anime,manga]);
  useEffect(()=>{
    const el=dialog.current;
    if(!open){if(el.open)el.close();launcher.current?.focus({preventScroll:true});return;}
    const old=document.body.style.overflow;document.body.style.overflow='hidden';if(!el.open)el.showModal();
    surface.current?.focus({preventScroll:true});
    return ()=>{document.body.style.overflow=old;if(el.open)el.close();};
  },[open]);
  function move(next){setStep(Math.max(0,Math.min(slides.length-1,next)));setInfo(false);surface.current?.focus({preventScroll:true});}
  function key(event){if(info){if(event.key==='Escape'){event.preventDefault();closeInfo();}return;}if(event.target.closest('select,input,textarea'))return;if(event.target===surface.current && (event.key===' '||event.key==='Enter')){event.preventDefault();move(step+1);return;}if(event.key==='ArrowRight'){event.preventDefault();move(step+1);}if(event.key==='ArrowLeft'){event.preventDefault();move(step-1);}}
  function tap(event){if(info||Date.now()<suppressClick.current||event.target.closest('button,a,select,input'))return;const rect=event.currentTarget.getBoundingClientRect();move(step+(event.clientX-rect.left<rect.width*.28?-1:1));}
  function pointerDown(event){if(!info&&!event.target.closest('button,a,select,input'))gesture.current={x:event.clientX,y:event.clientY};}
  function pointerUp(event){const start=gesture.current;gesture.current=null;if(!start||info)return;const dx=event.clientX-start.x,dy=event.clientY-start.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.4){suppressClick.current=Date.now()+400;move(step+(dx<0?1:-1));}}
  const fullTitles=slide.items|| (slide.item?[slide.item]:[]);
  return <><div className="fx-launch"><p>Your recap is ready.</p><button ref={launcher} className="button primary" onClick={()=>setOpen(true)}>Open my Wrapped ↗</button><span>Tap, swipe, or use the arrow keys.</span></div>
    <dialog ref={dialog} className="fx-dialog" aria-label="Your interactive Wrapped" onCancel={event=>{event.preventDefault();if(info)closeInfo();else setOpen(false);}} onKeyDown={key}>
      <div className="fx-atmosphere" aria-hidden="true">{(covers.length?covers:[{id:'art',cover:'/art/issue-cover.svg'}]).map((x,index)=><img key={`${x.id}-${index}`} src={x.cover} alt="" referrerPolicy="no-referrer" style={{'--i':index}}/>)}</div>
      <div className="fx-shell"><div className="fx-toolbar"><span>{anime.some(x=>x.isSample)?'FICTIONAL DEMO':'MW'} / {period==='all'?'ALL TIME':period}</span><div><button className="download-card" disabled={exporting} onClick={saveCard}>{exporting?"Saving…":"Download card ↓"}</button><button ref={infoTrigger} aria-label="About these numbers" aria-expanded={info} onClick={()=>setInfo(!info)}>ⓘ</button><button aria-label="Close recap" onClick={()=>setOpen(false)}>×</button></div></div>
      <div ref={surface} tabIndex={0} className="fx-card" data-theme={step%6} data-kind={slide.kind||'intro'} data-type={slide.type} onClick={tap} onPointerDown={pointerDown} onPointerUp={pointerUp} onPointerCancel={()=>{gesture.current=null;}} aria-label={`${slide.group}, card ${step+1} of ${slides.length}`}>
        <div className="fx-progress" role="progressbar" aria-label="Recap progress" aria-valuenow={step+1} aria-valuemin={1} aria-valuemax={slides.length}>{slides.map((x,index)=><span key={x.id} className={index<=step?'is-read':''}/>)}</div>
        <p className="fx-section">{slide.group}<span>{String(step+1).padStart(2,'0')} / {slides.length}</span></p>
        <div key={slide.id} className="fx-scene" inert={info} aria-hidden={info} aria-live="polite" aria-atomic="true"><Scene sample={anime.some(x=>x.isSample)||manga.some(x=>x.isSample)} slide={slide} data={data} period={period} name={name} avatar={avatar}/></div>
        <nav inert={info} aria-hidden={info} className="fx-nav" aria-label="Story controls"><button disabled={step===0} onClick={()=>move(step-1)} aria-label="Previous card">←</button><span>{step===0?'TAP TO BEGIN':slide.type==='closing'?'REPLAY ↗':'TAP OR SWIPE'}</span>{step<slides.length-1?<button onClick={()=>move(step+1)} aria-label={step===0?'Begin recap':'Next card'}>→</button>:<button onClick={()=>move(0)} aria-label="Replay recap">↺</button>}</nav>
        {info&&<section className="fx-info" aria-label="About these numbers"><button ref={infoClose} onClick={closeInfo} aria-label="Close information">×</button><h2>Behind the numbers</h2><p>Snapshot: {asOf} (UTC). Annual totals use valid recorded finish dates, not a complete watch/read history. Undated activity and active repeats cannot be assigned to a year. All time includes previously completed titles currently being revisited.</p><p>Scores are your current MAL scores. Top anime includes TV series only. All highest scorers appear in the reveal; equal scores use title order, then ID. Categories show five entries. Current and planned lists are today’s snapshot, not additions during the selected year. Started counts require valid recorded start dates.</p><p>Repeat counts are recorded all-time counters, not dated events. Missing counters are unknown. Catalog episode/chapter lengths are not hours watched or activity within the chosen year.</p>{['anime','manga'].map(kind=><p key={kind}>{kind}: {data[kind].missingDates} completed titles lack a full valid finish date; {data[kind].issues.future} have future dates; {data[kind].issues.reversed} have reversed dates; {data[kind].issues.activeRepeat} are being revisited.</p>)}{fullTitles.length>0&&<><h3>On this card</h3><ul>{fullTitles.map(x=><li key={x.id}>{x.title}</li>)}</ul></>}</section>}
      </div><p className="fx-bottom-hint" role="status">{exportMessage||"Your taste. Your story."}</p></div>
    </dialog></>;
}
